check_update_gui: False
auto_scroll: False
custom_names: []
sortie_times: 1
event_automation:
  event_folder: '20250930'
  plan_name: E11A夜战
  fleet_id: 2
  battle_count: 100
  reuse_daily_settings: False
  bonus_check_interval: 1800
use_quick_repair: True
preset_task:
  胖次:
    - [7-46SS-all2, 2, 10]
    - [9-2胖次, 4, 500]
  10把加成:
    - [9-3AD, 2, 10]
auto_restart: True
last_selected_task: 日常
max_restarts: 10
