check_update_gui: False
auto_scroll: True
custom_names:
  - "决战1"
  - "决战2"
  - "决战3"
  - "决战4"
  - "决战5"
  - "决战6"
  - "决战7"
  - "决战8"
  - "决战9"
  - "决战X"
sortie_times: 1
event_automation:
  event_folder: '20250930'
  plan_name: E11A夜战
  fleet_id: 2
  battle_count: 40
  reuse_daily_settings: False
  bonus_check_interval: 1800
use_quick_repair: False
preset_task:
  胖次:
    - [7-46SS-all2, 2, 10]
    - [9-2胖次, 4, 500]
