debug: False
log_level: INFO
check_update: False
delay: 3.0
dock_full_destroy: True
destroy_ship_work_mode: 0
destroy_ship_types:
  - 航母
  - 轻母
  - 装母
  - 导驱
remove_equipment_mode: True
bathroom_feature_count: 3
bathroom_count: 7

emulator_type: 蓝叠
emulator_name:
daily_automation:
  auto_expedition: True
  auto_gain_bonus: True
  auto_bath_repair: True
  auto_set_support: False
  auto_battle: False
  battle_type: 困难战列
  auto_exercise: False
  exercise_fleet_id: 3
  auto_normal_fight: True
  normal_fight_tasks:
    - [7-46SS-all2, 2, 10]
    - [9-2胖次, 4, 500]
  quick_repair_limit:
  stop_max_ship: True
  stop_max_loot: False

decisive_battle:
  chapter: 6
  level1: []
  level2: []
  flagship_priority: []
  repair_level: 2
  full_destroy: True
  useful_skill: True
  useful_skill_strict: True

ship_name_file: E:/AutoWSGR_GUI/resources/ship_name.yaml
plan_root: E:/AutoWSGR_GUI/plans

