"20250930":
  H-5:
    name: 钢铁磨盘(困难)
    nodes:
      A:
        is_start: True
        pos: [0.0698, 0.4594]
        connections: [C, E]
      B:
        is_start: True
        pos: [0.2752, 0.1943]
        connections: [F, G]
      C:
        pos: [0.1343, 0.7397]
        connections: [D]
      D:
        pos: [0.2594, 0.9058]
      E:
        pos: [0.3088, 0.5583]
        connections: [I, K]
      F:
        pos: [0.5490, 0.1826]
        connections: [M]
      G:
        pos: [0.3917, 0.3746]
        connections: [K, L]
      I:
        pos: [0.4398, 0.7797]
        connections: [J, K]
      J:
        pos: [0.6280, 0.9211]
      K:
        pos: [0.5727, 0.6101]
        connections: [M, O]
      L:
        pos: [0.5945, 0.4452]
        connections: [M]
      M:
        pos: [0.7926, 0.3899]
        connections: [N, O]
      N:
        pos: [0.9243, 0.6419]
      O:
        pos: [0.8058, 0.8104]

"20260104":
  H-5:
    name: "吹响号角"
    nodes:
      A:
        is_start: True
        pos: [0.3213, 0.8233]
        connections: [D, E, F]
      B:
        is_start: True
        pos: [0.1968, 0.6148]
        connections: [C, F]
      C:
        pos: [0.1797, 0.3486]
      D:
        detourable: True
        pos: [0.5174, 0.8516]
        connections: [G, J]
      E:
        pos: [0.4937, 0.7114]
        connections: [J, K]
      F:
        pos: [0.3687, 0.4723]
        connections: [K]
      G:
        pos: [0.6906, 0.9093]
        connecctions: [H,I]
      H:
        pos: [0.9177, 0.8787]
      I:
        pos: [0.8144, 0.6702]
      J:
        pos: [0.7373, 0.4876]
        connections: [K, L, M]
      K:
        detourable: True
        pos: [0.5405, 0.4441]
        connections: [N]
      L:
        pos: [0.7367, 0.1519]
      M:
        pos: [0.5879, 0.1802]
        connections: [N]
      N:
        pos: [0.3693, 0.2768]
        connections: [O, P]
      O:
        pos: [0.2515, 0.0989]
      P:
        pos: [0.1080, 0.2403]